name: Upick CICD

# main branch에 push 되면 실행
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: CD Pipeline
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: ['16.0.0']
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_USERNAME }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            cd /home/upickadmin/Upick_BE
            git pull origin main
            npm ci
            npx prisma db pull
            npx prisma generate
            npm run build
            npm run start:prod
